### ISSUE TITLE
Implementation for MySqlConnection Needed

### ISSUE THREAD

**Issue by lebensterben** [WinVector/rqdatatable#3]
Hi,

I was trying to join two tables from a remote MySQL database.
Currently rquery can do this job well, but when I try to execute the same query with rqdatatable::ex_data_table(), it says
```
Error in ex_data_table.default(conn, optree) : 
  rqdatatable::ex_data_table() does not have an implementation for class:  MySQLConnection yet
```
Do you have plan to add MySQLConnection support in the near future?

Thanks

**Comment by JohnMount** [comment]
rqdatatable is only for in-memory data.frames.  To work with MySQL you just use rquery.  The command to run in rquery would be execute() or materialize().  Some database examples can be found [here](https://github.com/WinVector/rquery/tree/master/db_examples).

**Comment by lebensterben** [comment]
>rqdatatable is only for in-memory data.frames.  To work with MySQL you just use rquery.  The command to run in rquery would be execute() or materialize().  Some database examples can be found [here](https://github.com/WinVector/rquery/tree/master/db_examples).

@JohnMount Thanks.

Just for clarification, if it's only for in-memory data.frames, then what's the advantage of using rqdatatable instead of data.table?
As for rquery, is it just a query generator?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnMount** [comment]
rquery is "just a query generator."  For in-memory rqdatatable is the same grammar as rquery, but has no advantage of data.table (which I am in fact a fan of).

**Comment by lebensterben** [comment]
>rquery is "just a query generator."  For in-memory rqdatatable is the same grammar as rquery, but has no advantage of data.table (which I am in fact a fan of). 

@JohnMount thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
