### ISSUE TITLE
What is the "ei" argument in extend_nse?

### ISSUE THREAD

**Issue by heoa** [WinVector/rqdatatable#5]
In creating the data pipeline, I am getting the following error

`> local_td(res) %.>% extend_nse(.,revSes := sum(rev)/sum(Ses), partitionby = c('date','ID'),) Error in tokenize_for_SQL(ei, colnames = have, env = env) :    argument "ei" is missing, with no default
`
which I solve by 

`local_td(res) %.>% extend_nse(.,revSes := sum(rev)/sum(Ses), partitionby = c('date','ID'),ei=1)`

but I cannot find what the `ei` is. So what is the "ei" argument in extend_nse?

**Comment by heoa** [comment]
This must be some typo somewhere in the following commands, I am not getting it anymore when I simplified the code. I will close this untill able to reproduce again.

**Comment by JohnMount** [comment]
`ei` is a name the internal parser/tokenizer uses for an intermediate expression.  My guess is the typo was the trailing comma in `,)` in the first line of code in your example- which possibly led to an undefined intermediate expression.  In `R` trailing commas can usually not allowed (unlike in `Python`).
